In [1]:
# import the required libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report,confusion_matrix

In [2]:
# Load the dataset
dataset  = pd.read_csv("./diabetes.csv")
dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
# Prepare the dataset in the required format
X = dataset.drop('Outcome', axis = 1)
Y = dataset['Outcome']


In [5]:
# Split the dataset
X_train, X_test, Y_train, Y_test =\
train_test_split(X, Y, test_size = 0.3)

In [6]:
# Build the model
model = SVC(kernel = 'linear')
model.fit(X_train, Y_train)

SVC(kernel='linear')

In [7]:
# Predict and evaluate
Y_pred = model.predict(X_test)

print(classification_report(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.75      0.87      0.81       146
           1       0.69      0.51      0.59        85

    accuracy                           0.74       231
   macro avg       0.72      0.69      0.70       231
weighted avg       0.73      0.74      0.72       231

[[127  19]
 [ 42  43]]


In [8]:
model = SVC()
model.fit(X_train, Y_train)
# Predict and evaluate
Y_pred = model.predict(X_test)

print(classification_report(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.73      0.91      0.81       146
           1       0.74      0.44      0.55        85

    accuracy                           0.74       231
   macro avg       0.74      0.67      0.68       231
weighted avg       0.74      0.74      0.72       231

[[133  13]
 [ 48  37]]


In [9]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']

dataset = pd.read_csv(url, names = colnames)
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [10]:
# Prepare the dataset in the required format
X = dataset.drop('class', axis = 1)
Y = dataset['class']

# Split the dataset
X_train, X_test, Y_train, Y_test = train_test_split(X, Y,
                                                    test_size = 0.3)
# Build the model
model = SVC(kernel = 'poly', degree = 4, 
            decision_function_shape = 'ovo')
model.fit(X_train, Y_train)
# Predict and evaluate
Y_pred = model.predict(X_test)

print(classification_report(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        18
Iris-versicolor       1.00      1.00      1.00        14
 Iris-virginica       1.00      1.00      1.00        13

       accuracy                           1.00        45
      macro avg       1.00      1.00      1.00        45
   weighted avg       1.00      1.00      1.00        45

[[18  0  0]
 [ 0 14  0]
 [ 0  0 13]]


In [11]:
from sklearn.datasets import load_iris
from sklearn.multiclass import OneVsOneClassifier
from sklearn.svm import LinearSVC

X, Y = load_iris(return_X_y=True)
# Split the dataset
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3)
# Build the model
model = OneVsOneClassifier(LinearSVC())
model.fit(X_train, Y_train)
# Predict and evaluate
Y_pred = model.predict(X_test)

print(classification_report(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       0.93      0.82      0.87        17
           2       0.77      0.91      0.83        11

    accuracy                           0.91        45
   macro avg       0.90      0.91      0.90        45
weighted avg       0.92      0.91      0.91        45

[[17  0  0]
 [ 0 14  3]
 [ 0  1 10]]


C:\Users\Venkat\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


In [9]:
#sklearn.multiclass